version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: govchime_db
    environment:
      POSTGRES_USER: govchime
      POSTGRES_PASSWORD: govchime_secure_password
      POSTGRES_DB: govchime
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U govchime"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: